config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :carts, only: [:show, :create, :update, :destroy] do
    get 'purchase' => 'carts#purchase', as: 'purchase'
  end
  resources :solds, only: [:show, :create]
  resources :genres, only: [:show]
  resources :songs, only: [:new, :create]
  resources :cds, only:[:show, :new, :create, :destroy, :edit, :update] do 
    resources :cd_comments, only:[:show, :create, :edit, :destroy, :update]
  end
  resources :admins do
    resources :cds, only: [:new, :create, :destroy, :edit, :update]
    resources :users, only: [:show, :edit, :update, :destroy, :index]
    resources :solds, only: [:index, :update]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
  root 'cds#index'
  get 'admins/:admin_id/top' => 'admins#top', as: 'admin_root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
   get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	# cartレコードをdestoryメソッドで削除したら、Railsがそのcartに紐づいていたcart_itemを全て削除してくれる
	has_many :solds
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cd
	belongs_to :cart
end

app/models/cd.rb
class Cd < ApplicationRecord
	has_many :songs, dependent: :destroy, inverse_of: :cd
	attachment :image
	accepts_nested_attributes_for :songs, allow_destroy: true
	belongs_to :genre, inverse_of: :cds
	has_many :cart_items
	has_many :sold_items
	with_options presence: true do
	validates :jacket_name
	validates :genre_id
	validates :remaining_quantity
	validates :disk
	validates :price
	validates :release_date
	validates :rabel_name
	end
	has_many :cd_comments
end

app/models/cd_comment.rb
class CdComment < ApplicationRecord
	belongs_to :user
	belongs_to :cd
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :cds, inverse_of: :genre
end

app/models/sold.rb
class Sold < ApplicationRecord
	has_many :sold_items
	belongs_to :cart, optional: true
	 belongs_to :user
	 has_many :cds
  before_create :accept
include AASM

aasm do
  state :not_accept, :initial => true
  state :受付中
  state :準備中
  state :発送済み

  event :accept do
    transitions  :from => :not_accept, :to => :受付中
  end

  event :preparate do
    transitions :from => :受付中, :to => :準備中
  end

  event :ship do
    transitions :from => [:受付中, :準備中], :to => :発送済み
  end
end
end

app/models/sold_item.rb
class SoldItem < ApplicationRecord
	belongs_to :sold
	belongs_to :cd
	has_many :cd_comments
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd, optional: true, inverse_of: :songs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :solds
  has_many :sold_items
  has_many :cd_comments

  soft_deletable

#論理削除済みのユーザーが再びログインできないようにする
  def self.find_for_authentication(warden_conditions)
    without_soft_destroyed.where(email: warden_conditions[:email]).first
  end
end

app/controllers/cds_controller.rb
class CdsController < ApplicationController
  before_action :create_cart
  def new
    @cd = Cd.new
    respond_to do |format|
            format.js  #{}
            # format.html{ redirect_to admin_root_path(current_admin.id), notice: 'Cd was successfully created.' }
        end
    @cd.songs.build
  end
  def create
  	@cd = Cd.new(cd_params)

      if @cd.save
        redirect_to admin_root_path(current_admin.id)
      else
      @cds = Cd.all.order(created_at: 'desc')
      render admin_root_path(current_admin.id)
      end
  end

  def show
    @cd = Cd.find(params[:id])
    @songs = @cd.songs.all
    if user_signed_in?
      @cart = current_user.cart
      @cart_item = CartItem.new
    end
    @cd_comment = CdComment.new
    @cd_comments = CdComment.all
  end

  def index
    if @results
   @cds = @results
   else
    @cds = Cd.all
   end
  end

  def edit
    @cd = Cd.find(params[:id])
  end

  def update
    cd = Cd.find(params[:id])
    cd.update(cd_params)
    redirect_to cd_path

  end

  def destroy
    cd = Cd.find(params[:id])
    cd.destroy
    redirect_to admin_root_path(current_admin.id)
  end

private

  def cd_params
    params.require(:cd).permit(:genre_id,:jacket_name,:image,:disk,:remaining_quantity,:release_date,:rabel_name,:artist_name,:price,
        songs_attributes: [:id,:song_name,:order,:_destroy])
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/solds_helper.rb
module SoldsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for @cd, url: admin_cds_path do |f| %>

    <% if @cd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cd.errors.count, "error") %> prohibited this cd from being saved:</h2>
      <ul>
        <% @cd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="modal-header">
      <h3 class="modal-title" id="exampleModalLabel">CD Infomation</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <div aria-hidden="true">&times;</div>
      </button>
    </div>
    <div class="modal-body">
      <div class="form-group field">
      <%= f.label :"ジャンル" %>
      <%= f.select :genre_id,  [["J-POP", 1],["ROCK", 2],["JAZZ", 3],["POP", 4],["演歌", 5]]  %>
      </div>
      <div class="form-group">
        <%= f.label :jacket_name, "ジャケット", class: "form-control-label"%>
        <%= f.text_field :jacket_name, class: "form-control", placeholder: "Enter Jacket" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :image %>
      </div>
      <div class="form-group">
        <%= f.label :disk, min: 1, class: "form-control-label" %>
        <%= f.text_field :disk, class: "form-control", placeholder: "Enter Disk" %>
      </div>
      <div class="form-group">
        <%= f.label :remaining_quantity, "在庫", class: "form-control-label" %>
        <%= f.number_field :remaining_quantity, class: "form-control", placeholder: "Enter Quantiy" %>
      </div>
      <div class="form-group">
        <%= f.label :release_date, "発売日", class: "form-control-label" %>
        <%= f.date_field :release_date, class: "form-control", placeholder: "Enter Release Date" %>
      </div>
      <div class="form-group">
        <%= f.label :rabel_name, "レーベル", class: "form-control-label"%>
        <%= f.text_field :rabel_name, class: "form-control", placeholder: "Enter Rabel" %>
      </div>
      <div class="form-group">
        <%= f.label :artist_name, "アーティスト", class: "form-control-label" %>
        <%= f.text_field :artist_name, class: "form-control", placeholder: "Enter Artist" %>
      </div>
      <div class="form-group">
        <%= f.label :price, "価格", class: "form-control-label" %>
        <%= f.number_field :price, class: "form-control", placeholder: "Enter Price"%>円
      </div>

      <div class="field">
      <table class="table table-striped table-bordered table-hover">
        <tbody>
          <tr>
            <th>曲順</th>
            <th>曲名</th>
            <th>アクション</th>
          </tr>
          <%= f.nested_fields_for :songs, wrapper_tag: :tr do |q| %>
            <td><%= q.number_field :order, min: 1, class: 'form-control' %></td>
            <td><%= q.text_field   :song_name,     class: 'form-control', placeholder: "Enter Song Name" %></td>
            <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
          <% end %>
        </tbody>
      </table>
      <%= f.add_nested_fields_link :songs, 'Add new', class: 'btn btn-primary', role: 'button' %>
      </div>
    </div>
    <div class="modal-footer actions">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">Close</button>
      <%= f.submit "CDを登録", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/show.html.erb
<div class = "cd-show clearfix">
	<div class = "cd-show-header"><h2><%=  @cd.artist_name %></h2></div>
	<div class="main-contents clearfix">
  <dl>
    <dd><%= attachment_image_tag @cd, :image, :fill, 60, 60, format: 'jpg',fallback: "no_image.jpg", class: "index-image" %></dd>

    <dt>ジャケット：<%= @cd.jacket_name %></dt>
    <dd>発売日：<%=  @cd.release_date %></dd>
    <dd>価格：<%=  @cd.price %>円</dd>
    </dl>
    </div>
    <p>Disk<%= @cd.disk %></p>
    <ul>
    <% @songs.each do |song| %>
		<li><%= song.order %>.<%= song.song_name %></li>
    <% end %>
  </ul>
  
</div>

app/views/admins/top.html.erb
<html>
<head>
  <title>Team Develop</title>
</head>
<body>
	<!-- header -->

	<!-- main-visual -->
<!-- <h2 style="margin-left: 50px;">New Albums!!</h2>
		<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
		<script src="infiniteslidev2.js"></script>

			<script type="text/javascript">
			$(function(){
			$('.infiniteslide').infiniteslide({
			'speed': 100, //速さ　単位はpx/秒です。
			'direction': 'left', //up/down/left/rightから選択
			'pauseonhover': true, //マウスオーバーでストップ
			'responsive': false, //子要素の幅を%で指定しているとき
			'clone': 1 //子要素の複製回数
			});
			});
			</script>


			<ul class="infiniteslide">
				<li><img class="release-image"	alt="" src="/assets/neon_night.jpg" ></li>
				<li><img class="release-image"	alt="" src="/assets/asiangirl.jpg"></li>
				<li><img class="release-image"	alt="" src="/assets/blackguy.jpg"></li>
				<li><img class="release-image" alt=""  src="/assets/book_shelf.jpg"></li>
				<li><img class="release-image" alt=""  src="/assets/boy_screaming.jpg"></li>
				<li><img class="release-image" alt=""  src="/assets/alice.jpg"></li>
				<li><img class="release-image" alt=""  src="/assets/headphone.jpg"></li>
				<li><img class="release-image" alt=""  src="/assets/cutelady.jpg"></li>
			</ul>
 -->


	<!-- main -->
	<main>
			<%= link_to 'New CD', new_admin_cd_path(current_admin.id),remote: true, class: "btn btn-lg btn-primary" %>
			<div class="modal fade" id="cd-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
			<div class="production-group clearfix">
				<% @cds.each do |cd| %>
				<div class="production-content">
					<%= link_to(cd) do %>
          				<%= attachment_image_tag(cd, :image, class:'production' ) %>
        			<% end %>
					<p><%= link_to cd.jacket_name, cd_path(cd.id) %></p>
					<p><%= cd.artist_name %></p>
				</div>
				<% end %>
			</div>

			<!-- <h2 class="product-headline"> 商品一覧 </h2>
			<% @cds.each do |cd| %>
				<div class = "cds-index">
					<dl>
    				<dd><%= attachment_image_tag cd, :image, :fill, 60, 60, format: 'jpg',fallback: "no_image.jpg", class: "index-image" %></dd>
     				 <dt>ジャケット：<%= link_to cd.jacket_name, admin_cd_path(current_admin.id, cd.id) %></dt>
      				<dd>発売日：<%=  cd.release_date %></dd>
      				<dd>アーティスト：<%=  cd.artist_name %></dd>
      				<dd>価格：<%=  cd.price %>円</dd>
 					</dl>
    		</div>
			<% end %> -->
    		
			<div class="paginate">
				<p><<</p>
				<p><</p>
				<p>1</p>
				<p>2</p>
				<p>3</p>
				<p>></p>
				<p>>></p>
			</div>
		

	</main>


	<!-- footer -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>
  <body>
  <header class="clearfix">
    <!-- <i class="fa fa-facebook-square icon"></i> -->
    <!-- <div class="kensaku">。。このWebsiteを検索</div> -->
    
  <div class="genre">
    <div class="genre-box">
      <div class="genre-item">
        <%= link_to(genre_path(1)) do %>
          <span>Jpop</span>
          <span>J-ポップ</span>
        <% end %>
      </div>
    </div>
    <div class="genre-box">
      <div class="genre-item">
        <%= link_to(genre_path(2)) do %>
          <span>Rock</span>
          <span>ロック</span>
        <% end %>
      </div>
    </div>
    <div class="genre-box">
      <div class="genre-item">
        <%= link_to(genre_path(3)) do %>
          <span>Jazz</span>
          <span>ジャズ</span>
        <% end %>
      </div>
    </div>
    <div class="genre-box">
      <div class="genre-item">
        <%= link_to(genre_path(4)) do %>
          <span>Enka</span>
          <span>演歌</span>
        <% end %>
      </div>
    </div>
    <div class="genre-box">
      <div class="genre-item">
        <%= link_to(genre_path(5)) do %>
          <span>Import Music</span>
          <span>洋楽</span>
        <% end %>
      </div>
    </div>
  </div>
   <% if admin_signed_in? %>
    <h1 class="headline">
      <%= link_to "管理者画面", admin_root_path(current_admin.id) %>
    </h1>
    <% end %>
<div class = "cd_search_area"> 
<% if admin_signed_in? %>
    <!-- `form_for`のRansack版 -->
  <%= search_form_for @search, url: admin_root_path(current_admin.id) do |f| %>
  <!-- # nameカラムに対して部分一致検索ができる -->
  <%= f.search_field :jacket_name_or_artist_name_cont, class: "ransack-form", placeholder: "例..アーティスト名、ジャケット名" %>
  <%= button_tag :type => "submit", :class =>"ransack" do %>
  <i class="fas fa-search"></i>
  <% end %>

  <% end %>
  <% else %>
  <%= search_form_for @search, url: root_path do |f| %>
  <!-- # nameカラムに対して部分一致検索ができる -->
  <%= f.search_field :jacket_name_or_artist_name_cont, class: "ransack-form", placeholder: "例..アーティスト名、ジャケット名" %>
  <!-- <i class="fas fa-search"></i> -->
  <%= button_tag :type => "submit", :class =>"ransack" do %>
  <i class="fas fa-search"></i>
  <% end %>
  
  <% end %>

<% end %>
</div>
    <% if user_signed_in? %>
      <div class="user-box">
        <a href="/carts/:id">
          <i class="fa fa-shopping-cart cart"></i></a>
        <div class="name">
          <%= link_to(user_path(current_user)) do  %>
            <i class="fa fa-user-circle usericon"></i>
            <%= current_user.last_name %>
          <% end %>
        </div>
      </div>
      <% elsif admin_signed_in? %>
      
    <% else %>
      <div class="login-signup">
        <p class="lo-si"><a href="/users/sign_in">Login</a></p>
        <p class="lo-si"><a href="/users/sign_up">Sign up</a></p>
      </div>
    </div>
    <% end %>
    <% if admin_signed_in? %>
    <nav class="admin-nav">
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "購入履歴", admin_solds_path(current_admin.id), class: "nav-text" %>
        </li>
        <li class="nav-list-item">
          <%= link_to 'User一覧', admin_users_path(current_admin.id), class: "nav-text" %>
        </li>
        <li class="nav-list-item"><%= link_to 'logout', destroy_admin_session_path(current_admin.id), class: "glyphicon glyphicon-log-out nav-text",method: :delete %></li>
      </ul>
      </nav>
      <% end %>
</header>
  <%= yield %>
  <footer>
    <p class="footer-text"> ©︎ All rights recerved by Omomuki.Inc.</p>
  </footer>
  </body>
  </html>