config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :carts, only: [:show, :create, :update, :destroy] do
    get 'purchase' => 'carts#purchase', as: 'purchase'
  end
  resources :solds, only: [:show, :create]
  resources :genres, only: [:show]
  resources :songs, only: [:new, :create]
  resources :cds, only:[:show, :new, :create, :destroy, :edit, :update] do 
    resources :cd_comments, only:[:show, :create, :edit, :destroy, :update]
  end
  resources :admins do
    resources :cds, only: [:new, :create, :destroy, :edit, :update]
    resources :users, only: [:show, :edit, :update, :destroy, :index]
    resources :solds, only: [:index, :update]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
  root 'cds#index'
  get 'admins/:admin_id/top' => 'admins#top', as: 'admin_root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
   get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :solds
  has_many :sold_items
  has_many :cd_comments

  soft_deletable

#論理削除済みのユーザーが再びログインできないようにする
  def self.find_for_authentication(warden_conditions)
    without_soft_destroyed.where(email: warden_conditions[:email]).first
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :address, :tell_number, :email, :post_code])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @solds = @user.solds.order(created_at: 'desc')
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if admin_signed_in?
        redirect_to admin_user_path(current_admin.id, @user.id)
      elsif user_signed_in?
        redirect_to user_path(current_user)
      end
    elsif admin_signed_in?
        redirect_to edit_admin_user_path(current_admin.id, @user.id)
    else
      render "edit"
    end
end

  def index
    @users = User.all

  end

  def destroy
    user = User.find(params[:id])
    if user.soft_destroy
    redirect_to logout_path
  end
end

  private
	def user_params
	    params.require(:user).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :address, :post_code, :tell_number)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div style="width:320px;margin:0 auto;">
	<h1>User Info</h1>
		<%= form_for(@user) do |f| %>

		  <h4>お名前</h4>
		  <%= f.text_field :last_name %><%= f.text_field :first_name %>

		  <h4>カナ</h4>
		  <%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %>

		  <h4>Tell</h4>
		  <%= f.text_field :tell_number %>

		  <h4>PostCode</h4>
		  <%= f.text_field :post_code %>

		  <h4>Address</h4>
		  <%= f.text_field :address %>

		  <br>
		  <div style="width:160px;">
		  	<%= f.submit '更新' %>
		  </div>

		<% end %>
		<% if user_signed_in? %>
		<%= link_to "前に戻る", user_path(current_user.id)%>
		<% elsif admin_signed_in? %>
		<%= link_to "前に戻る", admin_user_path(current_admin.id, @user.id)%>
		<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="col-xs-8 clearfix">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
        <thead>
            <tr> 
              <th>name</th>
              <th colspan="3"></th>
            </tr>
        </thead>
    <% @users.each do |user| %>
        <tbody>
        <tr>
            <td><%=  user.last_name %> <%=  user.first_name %></td>
            <td><%=  user.last_name_kana %> <%=  user.first_name_kana %></td>
            <td><%= link_to "Show", admin_user_path(current_admin.id, user.id)%></td>
        </tr>
        </tbody>
    <% end %>
    </table>
<h1>あああ</h1>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
		<div class="col-lg-4">
			<h1>My page</h1>
			<table class="table">
				<tr>
					<td>Name</td>
					<td><%= @user.last_name %><%= @user.first_name %></td>
				</tr>
				<tr>
					<td>カナ</td>
					<td><%= @user.last_name_kana %><%= @user.first_name_kana %></td>
				</tr>
				<tr>
					<td>Tell</td>
					<td><%= @user.tell_number %></td>
				</tr>
				</tr>
					<tr>
					<td>Email</td>
					<td><%= @user.email %></td>
				</tr>
				<tr>
					<td>Address</td>
					<td><%= @user.address %></td>
				</tr>
					<tr>
					<td>PostCode</td>
					<td><%= @user.post_code %></td>
				</tr>
			</table>
			<% if user_signed_in? %>
			<%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
			<% elsif admin_signed_in? %>
			<%= link_to "", edit_admin_user_path(current_admin, @user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
			<% end %>

			<br>
			<% if user_signed_in? %>
			<%= link_to destroy_user_session_path, method: :delete do %>
				 <button type="button" class="btn btn-default btn-block">
				    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
				    <span>Logout</span>
				 </button>
			<% end %>

			<%= link_to user_path(current_user), method: :delete do %>
				<button type="button" class="btn btn-danger">退会する
				</button>
			<% end %>
			<% elsif admin_signed_in? %>
			<%= link_to user_path(@user.id), method: :delete do %>
				<button type="button" class="btn btn-danger">退会させる
				</button>
			<% end %>
			<% end %>
			<br>
			<br>
		</div>
	<div class="col-lg-8">
			<h2>購入履歴</h2>
			<% @solds.each do |sold| %>
			<div class="sold-box">
				<div class="sold-box-header">
					<div class="sold-box-header-inner">
						<div class="sold-box-header-left">
							<div class="sold-row">
								<a class="sold-row-label">注文日</a>
							</div>
							<div class="sold-row-secondary">
								<%= sold.created_at.strftime('%Y/%m/%d')%>
							</div>
						</div>
						<div class="sold-box-header-left-secondary">
							<div class="sold-row">
								<a class="sold-row-label">合計</a>
							</div>
							<div class="sold-row-secondary">
								<%= sold.subtotal %> 円
							</div>
						</div>
						<div class="sold-box-header-right">
							<div class="sold-row">
								<a class="sold-row-label">注文状況</a>
							</div>
							<div class="sold-row-secondary">
								<% if admin_signed_in? %>
								<%=button_to sold.aasm_state, admin_sold_path(current_admin.id, sold.id), method: :put %>
								<% else %>
								<%=sold.aasm_state%></td>
								<% end %>
							</div>
						</div>
					</div>
				</div>
				<% sold.sold_items.each do |sold_item| %>
				<div class="sold-box-body">
					<div class="sold-box-body-inner">
						<div class="sold-content clearfix">
							<div class="sold-content-image">
							<%= attachment_image_tag sold_item.cd, :image, :fill, 100, 100, format: 'jpeg' %>
							</div>
							<div class="sold-content-details">
								<div class="sold-content-row">
									<%if admin_signed_in? %>
									<%=link_to sold_item.cd.jacket_name, admin_cd_path(current_admin.id,sold_item.cd.id), class: "sold-cd-jacketname" %>
									<% else %>
									<%=link_to sold_item.cd.jacket_name, cd_path(sold_item.cd.id), class: "sold-cd-jacketname" %>
									<% end %>
								</div>
								<div class="sold-content-row">
									<%= sold_item.cd.artist_name %>
								</div>
								<div class="sold-content-row">
									<%= sold_item.cd.rabel_name %>
								</div>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
			<% end %>
		</div>
</div>