config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :carts, only: [:show, :create, :update, :destroy] do
    get 'purchase' => 'carts#purchase', as: 'purchase'
  end
  resources :solds, only: [:show, :create]
  resources :genres, only: [:show]
  resources :songs, only: [:new, :create]
  resources :cds, only:[:show, :new, :create, :destroy, :edit, :update] do 
    resources :cd_comments, only:[:show, :create, :edit, :destroy, :update]
  end
  resources :admins do
    resources :cds, only: [:new, :create, :destroy, :edit, :update]
    resources :users, only: [:show, :edit, :update, :destroy, :index]
    resources :solds, only: [:index, :update]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
  root 'cds#index'
  get 'admins/:admin_id/top' => 'admins#top', as: 'admin_root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
   get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	# cartレコードをdestoryメソッドで削除したら、Railsがそのcartに紐づいていたcart_itemを全て削除してくれる
	has_many :solds
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cd
	belongs_to :cart
end

app/models/cd.rb
class Cd < ApplicationRecord
	has_many :songs, dependent: :destroy, inverse_of: :cd
	attachment :image
	accepts_nested_attributes_for :songs, allow_destroy: true
	belongs_to :genre, inverse_of: :cds
	has_many :cart_items
	has_many :sold_items
	with_options presence: true do
	validates :jacket_name
	validates :genre_id
	validates :remaining_quantity
	validates :disk
	validates :price
	validates :release_date
	validates :rabel_name
	end
	has_many :cd_comments
end

app/models/cd_comment.rb
class CdComment < ApplicationRecord
	belongs_to :user
	belongs_to :cd
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :cds, inverse_of: :genre
end

app/models/sold.rb
class Sold < ApplicationRecord
	has_many :sold_items
	belongs_to :cart, optional: true
	 belongs_to :user
	 has_many :cds
  before_create :accept
include AASM

aasm do
  state :not_accept, :initial => true
  state :受付中
  state :準備中
  state :発送済み

  event :accept do
    transitions  :from => :not_accept, :to => :受付中
  end

  event :preparate do
    transitions :from => :受付中, :to => :準備中
  end

  event :ship do
    transitions :from => [:受付中, :準備中], :to => :発送済み
  end
end
end

app/models/sold_item.rb
class SoldItem < ApplicationRecord
	belongs_to :sold
	belongs_to :cd
	has_many :cd_comments
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd, optional: true, inverse_of: :songs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :solds
  has_many :sold_items
  has_many :cd_comments

  soft_deletable

#論理削除済みのユーザーが再びログインできないようにする
  def self.find_for_authentication(warden_conditions)
    without_soft_destroyed.where(email: warden_conditions[:email]).first
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :create_cart
  def show
    @cart_items = current_cart.cart_items
  	@total_price = 0
  	@cart_items.each do |cart_item|
  	  @total_price += cart_item.price
    end
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cd_id = @cart_item.cd_id
    if current_cart.cart_items.find_by(cd_id: @cd_id)
      redirect_to cd_path(@cart_item.cd_id), alert: 'その商品は既にカートに入っています'
    else
      @cart_item.user_id = current_user.id
      @cart_item.cart_id = current_cart.id
      @cart_item.price = @cart_item.cd.price * @cart_item.quantity
      if @cart_item.quantity <= @cart_item.cd.remaining_quantity
        @cart_item.save
        redirect_to cd_path(@cart_item.cd_id)
      else
        redirect_to cd_path(@cart_item.cd_id), alert: '購入枚数は在庫よりも少なくしてください'
      end
    end
  end

  def update
  	# @cart_item.update(quantity: params[:quantity].to_i)
   #  redirect_to current_cart
  end

  def purchase
    @cart_items = current_cart.cart_items
  	@cart = current_cart
  	@user = current_user
  	@total_price = 0
  	@cart_items.each do |cart_item|
  	  @total_price += cart_item.price
    end
    @cart.subtotal = @total_price
    @cart.save
  	@sold_item = SoldItem.new
  end

  def destroy
  	@cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to root_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:user_id, :cd_id, :quantity, :cart_id, :price)
  end
end

app/controllers/cds_controller.rb
class CdsController < ApplicationController
  before_action :create_cart
  def new
    @cd = Cd.new
    respond_to do |format|
            format.js  #{}
            # format.html{ redirect_to admin_root_path(current_admin.id), notice: 'Cd was successfully created.' }
        end
    @cd.songs.build
  end
  def create
  	@cd = Cd.new(cd_params)

      if @cd.save
        redirect_to admin_root_path(current_admin.id)
      else
      @cds = Cd.all.order(created_at: 'desc')
      render admin_root_path(current_admin.id)
      end
  end

  def show
    @cd = Cd.find(params[:id])
    @songs = @cd.songs.all
    if user_signed_in?
      @cart = current_user.cart
      @cart_item = CartItem.new
    end
    @cd_comment = CdComment.new
    @cd_comments = CdComment.all
  end

  def index
    if @results
   @cds = @results
   else
    @cds = Cd.all
   end
  end

  def edit
    @cd = Cd.find(params[:id])
  end

  def update
    cd = Cd.find(params[:id])
    cd.update(cd_params)
    redirect_to cd_path

  end

  def destroy
    cd = Cd.find(params[:id])
    cd.destroy
    redirect_to admin_root_path(current_admin.id)
  end

private

  def cd_params
    params.require(:cd).permit(:genre_id,:jacket_name,:image,:disk,:remaining_quantity,:release_date,:rabel_name,:artist_name,:price,
        songs_attributes: [:id,:song_name,:order,:_destroy])
  end

end

app/controllers/solds_controller.rb
class SoldsController < ApplicationController
  # before_action :current_sold
  # helper_method :current_sold

  def create
  	@sold = Sold.create(user_id: current_user.id, cart_id: current_cart.id, subtotal: current_cart.subtotal)
    @cart_items = current_cart.cart_items
  	# @sold_item = SoldItem.new(params[:id])
  	@cart_items.each do |cart_item|
  		@sold_item = SoldItem.new(params[:id])
  		@sold_item.cart_id = cart_item.cart_id
  		@sold_item.cd_id = cart_item.cd_id
  		@sold_item.quantity = cart_item.quantity
  		@sold_item.price = cart_item.price
  		@sold_item.user_id = cart_item.user_id
      @sold_item.sold_id = @sold.id
      @sold_item.save
      cart_item.cd.remaining_quantity -= cart_item.quantity
      cart_item.cd.save
  		cart_item.destroy
  	end
    current_cart.destroy
    redirect_to root_path, notice: '注文が完了しました。ご購入ありがとうございます！'
  end

  def index
    @solds = Sold.all.order(created_at: 'desc')
  end

  def show
  end

  def update
    sold = Sold.find(params[:id])
    # @user.id = sold.user_id
    if sold.aasm_state == '受付中'
      sold.preparate!
    elsif sold.aasm_state == '準備中'
      sold.ship!
    end
    redirect_to admin_solds_path(current_admin.id)
  end

  private
  def sold_item_params
  	params.require(:sold_item).permit(:user_id, :cd_id, :quantity, :cart_id, :price)
  end


  # def sold_params
  #   params.require(:sold).permit(:aasm_state)
  # end

  # def current_sold
  # 	if session[:sold_id]
  #     @sold = Sold.find(session[:sold_id])
  #       else
  #     @sold = Sold.create(user_id: current_user.id, cart_id: current_cart.id)
  #       session[:sold_id] = @sold.id
  #   end
  # end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cd_comments_helper.rb
module CdCommentsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/solds_helper.rb
module SoldsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/apdate.html.erb
<h1>Carts#apdate</h1>
<p>Find me in app/views/carts/apdate.html.erb</p>

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/purchase.html.erb
<body>
	<h1 class="topic">購入確認画面</h1>
	<div class="container">
		<div class="row">
			<div class="col-lg-1"></div>
			<section id="purchase">
				<div class="col-lg-3">
					<div class="left-content">
						<div class="content-item">
							<h2>お届け先</h2>
							<br>
							<p class="info-text"><b>名前:</b> <%= @user.last_name %><%= @user.first_name %></p>
							<p><b>お届け先住所:</b></p>
							<p>〒<%= @user.post_code %></p>
							<p class="info-text"><%= @user.address %></p>
							<p class="info-text"><b>電話番号:</b> <%= @user.tell_number %></p>
							<p><b>メールアドレス:</b> <%= @user.email %></p>
							<p><br></p>
							<%= link_to "トップページに戻る", root_path %>
						</div>
					</div>
				</div>
				<div class="col-lg-7">
					<div class="right-content">
						<div class="content-item">
							<table class="cart-contents">
								<thead>
									<tr>
										<th class="table-item"></th>
										<th class="table-item">商品名</th>
										<th class="table-item">アーティスト名</th>
										<th class="table-item">金額</th>
										<th class="table-item">数量</th>
									</tr>
								</thead>
								<tbody>
									<% @cart_items.each do |cart_item| %>
										<tr>
											<td class="table-item"><%= attachment_image_tag(cart_item.cd, :image, :fill, 100, 100) %></td>
											<td class="table-item"><%= cart_item.cd.jacket_name %></td>
											<td class="table-item"><%= cart_item.cd.artist_name %></td>
											<td class="table-item"><%= cart_item.price %></td>
											<td class="table-item"><%= cart_item.quantity %></td>
										</tr>
									<% end %>
								</tbody>
							</table>
							<h3 class="sum">合計金額：<%= @total_price %>円</h3>
							<% unless @cart_items.empty? %>
								<div class="btn-group">
									<%= form_for @sold_item, url: solds_path do |f| %>
	   									<%= f.hidden_field :cart_id, :value => current_cart.id %>
        								<%= f.submit "注文を確定する" %>
    								<% end %>
    							</div>
    						<% end %>
						</div>
					</div>
				</div>
			</section>
			<div class="col-lg-1"></div>
		</div>
	</div>
</body>

app/views/carts/show.html.erb
<body class="cart-background">
	<section id="cart">
		<h1 class="topic">カートの中身</h1>
		<p><br><br></p>
		<div>
			<table class="cart-item">
				<thead>
					<tr>
						<th class="cd-info"></th>
						<th class="cd-info">商品名</th>
						<th class="cd-info">アーティスト名</th>
						<th class="cd-info">金額</th>
						<th class="cd-info">数量</th>
					</tr>
				</thead>
				<tbody>
					<% @cart_items.each do |cart_item| %>
						<tr>
							<td class="cd-info"><%= attachment_image_tag(cart_item.cd, :image, :fill, 100, 100) %></td>
							<td class="cd-info"><%= cart_item.cd.jacket_name %></td>
							<td class="cd-info"><%= cart_item.cd.artist_name %></td>
							<td class="cd-info"><%= cart_item.price %></td>
							<td class="cd-info"><%= cart_item.quantity %></td>
							<td class="cd-info"><%= link_to 'カートから削除', cart_path(cart_item.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn-sm btn-danger'%></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<h3 class="sum">合計金額：<%= @total_price %>円</h3>
			<div class="btn-container">
				<% unless @cart_items.empty? %>
					<%= link_to(cart_purchase_path(current_cart.id)) do %>
						<div class="btn btn-lg btn-default btn-color btn-block">
							<p class="btn-font">購入手続きへ</p>
						</div>
					<% end %>
				<% end %>
			</div>
			<p class="back"><%= link_to "トップページに戻る", root_path %></p>
		</div>
	</section>
</body>

app/views/carts/update.html.erb
<h1>Carts#apdate</h1>
<p>Find me in app/views/carts/apdate.html.erb</p>

app/views/cds/edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for @cd, url: admin_cd_path do |f| %>

    <% if @cd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cd.errors.count, "error") %> prohibited this cd from being saved:</h2>
      <ul>
        <% @cd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="modal-header">
      <h3 class="modal-title" id="exampleModalLabel">CDを編集</h3>
      <%= link_to "編集を止める", admin_cd_path(current_admin.id, @cd.id), class: "btn-sm btn-default" %>
    </div>
    <div class="modal-body">
      <div class="form-group field">
      <%= f.label :"ジャンル" %>
      <%= f.select :genre_id,  [["J-POP", 1],["ROCK", 2],["JAZZ", 3],["演歌", 4]]  %>
      </div>
      <div class="form-group">
        <%= f.label :jacket_name, "ジャケット", class: "form-control-label"%>
        <%= f.text_field :jacket_name, class: "form-control", placeholder: "Enter Jacket" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :image %>
      </div>
      <div class="form-group">
        <%= f.label :disk, class: "form-control-label" %>
        <%= f.text_field :disk, class: "form-control", placeholder: "Enter Disk" %>
      </div>
      <div class="form-group">
        <%= f.label :remaining_quantity, "在庫", class: "form-control-label" %>
        <%= f.number_field :remaining_quantity, class: "form-control", placeholder: "Enter Quantiy" %>
      </div>
      <div class="form-group">
        <%= f.label :release_date, "発売日", class: "form-control-label" %>
        <%= f.date_field :release_date, class: "form-control", placeholder: "Enter Release Date" %>
      </div>
      <div class="form-group">
        <%= f.label :rabel_name, "レーベル", class: "form-control-label"%>
        <%= f.text_field :rabel_name, class: "form-control", placeholder: "Enter Rabel" %>
      </div>
      <div class="form-group">
        <%= f.label :artist_name, "アーティスト", class: "form-control-label" %>
        <%= f.text_field :artist_name, class: "form-control", placeholder: "Enter Artist" %>
      </div>
      <div class="form-group">
        <%= f.label :price, "価格", class: "form-control-label" %>
        <%= f.number_field :price, class: "form-control", placeholder: "Enter Price"%>円
      </div>

      <div class="field">
      <table class="table table-striped table-bordered table-hover">
        <tbody>
          <tr>
            <th>曲順</th>
            <th>曲名</th>
            <th>アクション</th>
          </tr>
          <%= f.nested_fields_for :songs, wrapper_tag: :tr do |q| %>
            <td><%= q.number_field :order, class: 'form-control' %></td>
            <td><%= q.text_field   :song_name,     class: 'form-control', placeholder: "Enter Song Name" %></td>
            <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
          <% end %>
        </tbody>
      </table>
      <%= f.add_nested_fields_link :songs, 'Add new', class: 'btn btn-primary', role: 'button' %>
      </div>
    </div>
    <div class="modal-footer actions">
      <%= link_to "編集を止める", admin_cd_path(current_admin.id, @cd.id), class: "btn-sm btn-default" %>
      <%= f.submit "CDを更新", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/cds/index.html.erb
<body>
	<section id="portfolio">
		<div class="container">
			<% if flash[:notice] %>
  				<div class="alert alert-success">
    				<%= flash[:notice] %>
  				</div>
			<% end %>
			<h2 class="heading">ALL</h2>
			<div class="production-group clearfix">
				<% @cds.each do |cd| %>
				<div class="production-content">
					<%= link_to(cd) do %>
          				<%= attachment_image_tag(cd, :image, class:'production' ) %>
        			<% end %>
					<p class="cd-content"><%= link_to cd.jacket_name, cd_path(cd.id) %></p>
					<p class="cd-content"><%= cd.artist_name %></p>
				</div>
				<% end %>
			</div>
		</div>
	</section>
</body>

app/views/cds/new.js.erb
$("#cd-modal").html("<%= escape_javascript(render 'admins/form') %>");
$("#cd-modal").modal("show");

app/views/cds/show.html.erb
<div class="container show">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-3">
            <%= attachment_image_tag(@cd, :image, class: "cd-image" ) %>
            <h5>発売日：<%=  @cd.release_date.to_date %></h5>
            <h5><%= @cd.genre.genre_name %></h5>
            <h5><%= @cd.rabel_name %></h5>
            <% if admin_signed_in? %>
                <p class="return"><%=link_to 'Topに戻る', admin_root_path(current_admin.id) %></p>
                <% else %>
                <p class="return"><%=link_to 'Topに戻る', root_path %></p>
            <% end %>
            <% if admin_signed_in? %>
                <dd><%=link_to 'Edit', edit_admin_cd_path(@cd.id), class: "btn-sm btn-success"%>    <%=link_to 'Destroy',admin_cd_path(current_admin.id), method: :delete, class: "btn-sm btn-danger"%></dd>
            <% end %>
        </div>
        <div class="col-lg-7">
            <div class="cd-group">
                <div class="show-header clearfix">
                    <div class="left-item">
                        <h2><%= @cd.jacket_name %></h2>
                        <h4><%=  @cd.artist_name %></h4>
                    </div>
                    <div class="right-item">
                        <h5>価格：<%=  @cd.price %>円</h5>
                        <h5>在庫<%= @cd.remaining_quantity%></h5>
                    </div>
                </div>
                <p><br></p>
                <table class="cart-contents">
                    <thead>
                        <tr>
                            <th><p>曲名</p></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @songs.each do |song| %>
                            <tr>
                                <td><p><%= song.order %>.  <%= song.song_name %></p></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <p><br></p>

            <% if flash[:alert] %>
                <div class="alert alert-danger">
                    <%= flash[:alert] %>
                </div>
            <% end %>
            <% if user_signed_in? %>
                <%= form_for [@cd, @cart_item], url:carts_path do |f| %>
                    <%= f.hidden_field :cd_id, :value => @cd.id %>
                    <%= f.label :購入枚数 %>
                    <%= f.number_field :quantity, min: 1 , class: "form-control" %>
                    <%= f.submit "カートに入れる", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                <% end %>
            <% end %>

        </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <br />
    <hr />
    <div class="row">
    <div class="col-lg-1"></div>
    <div class="row-secondary col-lg-8 clearfix">
        <h3 class="review-header">カスタマーレビュー</h3>
        <div class="review-summary">
        </div>
        <div class="review-area form-group field clearfix">
            <div class="review-row clearfix">
                <%= form_for [@cd, @cd_comment] do |f| %>
                <h4 class="review-header">トップカスタマーレビュー</h4>
                <div class="field" id="star">
                <%= f.label :star %>
                <%= f.hidden_field :star, id: :cd_comment_star %>
                </div>
                <script>
                $('#star').raty({
                size     : 36,
                half     : true,
                starHalf : '<%= asset_path('star-half.png') %>',
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                scoreName: 'cd_comment[star]',
                hints:       ['bad', 'poor', 'regular', 'good', 'gorgeous']
                });
                </script>
                <div class="review-title">
                <%= f.text_field :comment_title, class: "form-control", placeholder: "レビューの見出し" %>
                </div>
                <div class="review-body">
                <%= f.text_area :comment, class: "form-control", placeholder: "ここにCDのレビューを記入（必須）" %>
                </div>
                <%= f.submit "コメントする",  class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
            </div>
            <div>
            <% @cd_comments.each do |cd_comment| %>
                <div class="reviewer">
                    <%= cd_comment.user.last_name %>
                </div>
                <div class="review-star" id="star-show">
                </div>
                <div class="review-titile">
                   <%= cd_comment.comment_title%>
                </div>
                <div class="review-date">
                    <%= cd_comment.created_at.strftime('%Y/%m/%d')%>
                </div>
                <div class="review-content">
                    <%= cd_comment.comment %>
                </div>
                    <script>
                    $('#star-show').raty({
                    size     : 2,
                    half     : true,
                    starHalf : '<%= asset_path('star-half.png') %>',
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    scoreName: 'cd_comment[star]',
                    readOnly: true,
                    score: <%= cd_comment.star %>
                    });
                    </script>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/solds/index.html.erb
<div class="container" >
	<div class="col-lg-12">
	<h2>購入履歴</h2>
			<% @solds.each do |sold| %>
			<div class="sold-box">
				<div class="sold-box-header">
					<div class="sold-box-header-inner">
						<div class="sold-box-header-left">
							<div class="sold-row">
								<a class="sold-row-label">注文日</a>
							</div>
							<div class="sold-row-secondary">
								<%= sold.created_at.strftime('%Y/%m/%d')%>
							</div>
						</div>
						<div class="sold-box-header-left-secondary">
							<div class="sold-row">
								<a class="sold-row-label">合計</a>
							</div>
							<div class="sold-row-secondary">
								<%= sold.subtotal %> 円
							</div>
						</div>
						<div class="sold-box-header-right">
							<div class="sold-row">
								<a class="sold-row-label">注文者</a>
							</div>
							<div class="sold-row-secondary">
								<%=link_to sold.user.last_name, admin_user_path(current_admin.id, sold.user.id), class: "sold-user-name" %> 様
							</div>
						</div>
						<div class="sold-box-header-right-secondary">
							<div class="sold-row">
								<a class="sold-row-label">注文状況</a>
							</div>
							<div class="sold-row-secondary">
								<% if admin_signed_in? %>
								<%=button_to sold.aasm_state, admin_sold_path(current_admin.id, sold.id), method: :put %>
								<% else %>
								<%=sold.aasm_state%></td>
								<% end %>
							</div>
						</div>
					</div>
				</div>
				<% sold.sold_items.each do |sold_item| %>
				<div class="sold-box-body">
					<div class="sold-box-body-inner">
						<div class="sold-content clearfix">
							<div class="sold-content-image">
							<%= attachment_image_tag sold_item.cd, :image, :fill, 100, 100, format: 'jpeg' %>
							</div>
							<div class="sold-content-details">
								<div class="sold-content-row">
									<%if admin_signed_in? %>
									<%=link_to sold_item.cd.jacket_name, admin_cd_path(current_admin.id,sold_item.cd.id), class: "sold-cd-jacketname" %>
									<% end %>
									<%=link_to sold_item.cd.jacket_name, cd_path(sold_item.cd.id), class: "sold-cd-jacketname" %>
								</div>
								<div class="sold-content-row">
									<%= sold_item.cd.artist_name %>
								</div>
								<div class="sold-content-row">
									<%= sold_item.cd.rabel_name %>
								</div>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
			<% end %>
	</div>
</div>

app/views/solds/show.html.erb
<h1>Solds#show</h1>
<p>Find me in app/views/solds/show.html.erb</p>